"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import "./cv.css";
type Lang="en"|"de"|"ti";
type CV={id?:number;cv_title:string;template:string;first_name:string;last_name:string;email:string;phone:string;city:string;address:string;linkedin:string;profession:string;summary:string;experience:string;education:string;skills:string;languages:string;certifications:string};
const blank:CV={cv_title:"My Swiss CV",template:"classic",first_name:"",last_name:"",email:"",phone:"",city:"",address:"",linkedin:"",profession:"",summary:"",experience:"",education:"",skills:"",languages:"",certifications:""};
const T={
en:{back:"Dashboard",my:"My CVs",newcv:"New CV",title:"CV Studio",sub:"Build, design and save a professional Swiss CV.",details:"Personal details",profile:"Professional profile",design:"Choose your design",first:"First name",last:"Last name",cvtitle:"CV name",email:"Email",phone:"Phone",city:"City / Canton",address:"Address",linkedin:"LinkedIn / portfolio",profession:"Profession / target role",summary:"Professional summary",experience:"Work experience",education:"Education & training",skills:"Skills",languages:"Languages",certifications:"Certificates & courses",save:"Save CV",update:"Update CV",preview:"Live preview",empty:"Start entering your information to preview your CV.",saved:"Saved",hint:"Use one line for each item."},
de:{back:"Dashboard",my:"Meine CVs",newcv:"Neuer CV",title:"CV Studio",sub:"Erstelle, gestalte und speichere einen professionellen Schweizer CV.",details:"Persönliche Angaben",profile:"Berufsprofil",design:"Design auswählen",first:"Vorname",last:"Nachname",cvtitle:"CV-Name",email:"E-Mail",phone:"Telefon",city:"Ort / Kanton",address:"Adresse",linkedin:"LinkedIn / Portfolio",profession:"Beruf / Zielposition",summary:"Kurzprofil",experience:"Berufserfahrung",education:"Ausbildung & Weiterbildung",skills:"Kenntnisse",languages:"Sprachen",certifications:"Zertifikate & Kurse",save:"CV speichern",update:"CV aktualisieren",preview:"Live-Vorschau",empty:"Gib deine Angaben ein, um den CV zu sehen.",saved:"Gespeichert",hint:"Eine Zeile pro Eintrag."},
ti:{back:"ዋና ገጽ",my:"CVታተይ",newcv:"ሓድሽ CV",title:"CV Studio",sub:"ሞያዊ ናይ ስዊዘርላንድ CV ኣዳሉን ዓቅቡን።",details:"ውልቃዊ ሓበሬታ",profile:"ናይ ስራሕ ሓበሬታ",design:"ዲዛይን ምረጹ",first:"ስም",last:"ስም ኣቦ",cvtitle:"ስም CV",email:"ኢመይል",phone:"ተሌፎን",city:"ከተማ / ካንቶን",address:"ኣድራሻ",linkedin:"LinkedIn / Portfolio",profession:"ሞያ / እትደልይዎ ስራሕ",summary:"ሓጺር ናይ ሞያ መግለጺ",experience:"ተመኩሮ ስራሕ",education:"ትምህርትን ስልጠናን",skills:"ክእለት",languages:"ቋንቋታት",certifications:"ሰርቲፊኬትን ኮርስን",save:"CV ዓቅብ",update:"CV ኣሐድስ",preview:"ቀጥታ ምርኢት",empty:"CV ንምርኣይ ሓበሬታኹም ኣእትዉ።",saved:"ተዓቂቡ",hint:"ንነፍሲ ወከፍ ነገር ሓደ መስመር ተጠቐሙ።"}};
const templates=[["classic","Classic Sidebar","Navy"],["modern","Modern Dark","Teal"],["minimal","Minimal Clean","B&W"],["gold","Bold Gold","Gold"],["green","Elegant Green","Forest"],["corporate","Corporate Blue","Blue"]];
const api=()=>process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
export default function CVStudio(){
 const[lang,setLang]=useState<Lang>("en"),[form,setForm]=useState<CV>(blank),[saved,setSaved]=useState<CV[]>([]),[status,setStatus]=useState(""),[showSaved,setShowSaved]=useState(false); const t=T[lang];
 const load=async()=>{try{setSaved(await(await fetch(api()+"/api/v1/career/cv")).json())}catch{}};
 useEffect(()=>{load()},[]);
 const set=(k:keyof CV,v:string)=>setForm({...form,[k]:v});
 const lines=(v:string)=>v.split("\n").filter(Boolean);
 async function submit(e:FormEvent){e.preventDefault();setStatus("…");const id=form.id;const payload={...form};delete payload.id;try{const r=await fetch(api()+"/api/v1/career/cv"+(id?"/"+id:""),{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw 0;const data=await r.json();setForm(data);setStatus("✓ "+t.saved);load()}catch{setStatus("Save failed")}}
 function openCV(cv:CV){setForm(cv);setShowSaved(false);window.scrollTo({top:0,behavior:"smooth"})}
 function fresh(){setForm({...blank});setStatus("");setShowSaved(false)}
 return <main className="studio"><header><Link href="/">← {t.back}</Link><div className="topActions"><button onClick={()=>setShowSaved(!showSaved)}>{t.my} <b>{saved.length}</b></button><button onClick={fresh}>＋ {t.newcv}</button>{(["de","en","ti"] as Lang[]).map(l=><button className={lang===l?"on":""} onClick={()=>setLang(l)} key={l}>{l==="ti"?"ትግ":l.toUpperCase()}</button>)}</div></header>
 {showSaved&&<section className="drawer"><div><h2>{t.my}</h2><button onClick={()=>setShowSaved(false)}>×</button></div>{saved.length?saved.map(cv=><article key={cv.id} onClick={()=>openCV(cv)}><span>{cv.first_name?.[0]}{cv.last_name?.[0]}</span><div><strong>{cv.cv_title}</strong><small>{cv.first_name} {cv.last_name} · {cv.profession||"CV"}</small></div><b>→</b></article>):<p>No saved CVs yet.</p>}</section>}
 <section className="intro"><span>NEXORA · CV STUDIO</span><h1>{t.title}</h1><p>{t.sub}</p></section>
 <div className="builder"><form onSubmit={submit}>
 <h2>{t.details}</h2><label>{t.cvtitle}<input value={form.cv_title} onChange={e=>set("cv_title",e.target.value)}/></label>
 <div className="two"><label>{t.first}<input required value={form.first_name} onChange={e=>set("first_name",e.target.value)}/></label><label>{t.last}<input required value={form.last_name} onChange={e=>set("last_name",e.target.value)}/></label></div>
 <div className="two"><label>{t.email}<input type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></label><label>{t.phone}<input value={form.phone} onChange={e=>set("phone",e.target.value)}/></label></div>
 <div className="two"><label>{t.city}<input value={form.city} onChange={e=>set("city",e.target.value)}/></label><label>{t.address}<input value={form.address} onChange={e=>set("address",e.target.value)}/></label></div>
 <label>{t.linkedin}<input value={form.linkedin} onChange={e=>set("linkedin",e.target.value)}/></label>
 <h2>{t.profile}</h2><label>{t.profession}<input value={form.profession} onChange={e=>set("profession",e.target.value)}/></label><label>{t.summary}<textarea rows={4} value={form.summary} onChange={e=>set("summary",e.target.value)}/></label>
 {(["experience","education","skills","languages","certifications"] as const).map(k=><label key={k}>{t[k]}<textarea rows={4} value={form[k]} onChange={e=>set(k,e.target.value)}/><small>{t.hint}</small></label>)}
 <h2>{t.design}</h2><div className="templates">{templates.map(([id,name,badge])=><button type="button" key={id} onClick={()=>set("template",id)} className={"template "+id+(form.template===id?" selected":"")}><div className="mini"><i/><i/><i/><i/></div><span><strong>{name}</strong><em>{badge}</em></span></button>)}</div>
 <div className="saveRow"><button className="save">{form.id?t.update:t.save}</button><span>{status}</span></div></form>
 <aside><div className="previewHead"><span>{t.preview}</span><b>{form.template.toUpperCase()}</b></div>{form.first_name||form.last_name?<div className={"paper "+form.template}><div className="cvTop"><h1>{form.first_name} {form.last_name}</h1><h3>{form.profession}</h3><p>{[form.city,form.phone,form.email].filter(Boolean).join(" · ")}</p>{form.linkedin&&<p>{form.linkedin}</p>}</div>{form.summary&&<p className="summary">{form.summary}</p>}{[["EXPERIENCE",form.experience],["EDUCATION",form.education],["SKILLS",form.skills],["LANGUAGES",form.languages],["CERTIFICATES",form.certifications]].map(([h,v])=>v&&<section key={h}><h4>{h}</h4>{lines(v).map((x,i)=><p key={i}>• {x}</p>)}</section>)}</div>:<div className="empty">{t.empty}</div>}</aside></div>
 </main>}
