"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import Link from "next/link";
import "./cv.css";

type Lang="en"|"de"|"ti"; type Item={title:string,place:string,date:string,detail:string};
type CV={id?:number;cv_title:string;template:string;first_name:string;last_name:string;email:string;phone:string;city:string;address:string;linkedin:string;profession:string;summary:string;experience:string;education:string;skills:string;languages:string;certifications:string};
const blank:CV={cv_title:"My Swiss CV",template:"swiss",first_name:"",last_name:"",email:"",phone:"",city:"",address:"",linkedin:"",profession:"",summary:"",experience:"",education:"",skills:"",languages:"",certifications:""};
const templates=[["swiss","Swiss Professional","Clean sidebar"],["executive","Executive Sidebar","Premium"],["tech","Modern Tech","Contemporary"],["ats","Minimal ATS","Recruiter friendly"],["corporate","Corporate Blue","Business"],["elegant","Elegant","Refined"],["starter","Starter","Simple"],["health","Healthcare","Warm"]];
const api=()=>process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const labels={
en:{back:"Dashboard",my:"My CVs",new:"New CV",title:"Professional CV Builder",sub:"Create a polished Swiss CV, choose a design and export it as PDF.",photo:"Profile photo",upload:"Upload photo",remove:"Remove",personal:"Personal details",career:"Professional profile",name:"CV name",first:"First name",last:"Last name",email:"Email",phone:"Phone",city:"City / Canton",address:"Address",link:"LinkedIn / portfolio",role:"Profession / target role",summary:"Professional summary",work:"Work experience",edu:"Education",cert:"Certificates & courses",skills:"Skills",langs:"Languages",addWork:"+ Add experience",addEdu:"+ Add education",addCert:"+ Add certificate",position:"Position / qualification",company:"Company / school",date:"Dates",details:"Details / achievements",design:"Choose your design",save:"Save CV",update:"Update CV",download:"Download PDF",preview:"A4 Preview",saved:"Saved",empty:"Add your name to start the preview.",tip:"Tip: in the print window choose “Save as PDF” and disable browser headers/footers."},
de:{back:"Dashboard",my:"Meine CVs",new:"Neuer CV",title:"Professioneller CV Builder",sub:"Erstelle einen Schweizer CV, wähle ein Design und exportiere ihn als PDF.",photo:"Profilfoto",upload:"Foto hochladen",remove:"Entfernen",personal:"Persönliche Angaben",career:"Berufsprofil",name:"CV-Name",first:"Vorname",last:"Nachname",email:"E-Mail",phone:"Telefon",city:"Ort / Kanton",address:"Adresse",link:"LinkedIn / Portfolio",role:"Beruf / Zielposition",summary:"Kurzprofil",work:"Berufserfahrung",edu:"Ausbildung",cert:"Zertifikate & Kurse",skills:"Kenntnisse",langs:"Sprachen",addWork:"+ Erfahrung hinzufügen",addEdu:"+ Ausbildung hinzufügen",addCert:"+ Zertifikat hinzufügen",position:"Position / Abschluss",company:"Firma / Schule",date:"Zeitraum",details:"Details / Erfolge",design:"Design auswählen",save:"CV speichern",update:"CV aktualisieren",download:"PDF herunterladen",preview:"A4-Vorschau",saved:"Gespeichert",empty:"Gib deinen Namen ein, um die Vorschau zu starten.",tip:"Tipp: Im Druckfenster „Als PDF speichern“ wählen und Browser-Kopf-/Fusszeilen deaktivieren."},
ti:{back:"ዋና ገጽ",my:"CVታተይ",new:"ሓድሽ CV",title:"ሞያዊ CV መዳለዊ",sub:"ናይ ስዊዘርላንድ CV ኣዳሉ፣ ዲዛይን ምረጹን PDF ኣውጽኡን።",photo:"ስእሊ",upload:"ስእሊ ኣእቱ",remove:"ኣውጽእ",personal:"ውልቃዊ ሓበሬታ",career:"ናይ ሞያ ሓበሬታ",name:"ስም CV",first:"ስም",last:"ስም ኣቦ",email:"ኢመይል",phone:"ተሌፎን",city:"ከተማ / ካንቶን",address:"ኣድራሻ",link:"LinkedIn / Portfolio",role:"ሞያ / እትደልይዎ ስራሕ",summary:"ሓጺር መግለጺ",work:"ተመኩሮ ስራሕ",edu:"ትምህርቲ",cert:"ሰርቲፊኬትን ኮርስን",skills:"ክእለት",langs:"ቋንቋታት",addWork:"+ ተመኩሮ ወስኽ",addEdu:"+ ትምህርቲ ወስኽ",addCert:"+ ሰርቲፊኬት ወስኽ",position:"ስራሕ / ዲግሪ",company:"ትካል / ቤት ትምህርቲ",date:"ዕለታት",details:"ዝርዝር / ውጽኢት",design:"ዲዛይን ምረጹ",save:"CV ዓቅብ",update:"CV ኣሐድስ",download:"PDF ኣውርድ",preview:"A4 ምርኢት",saved:"ተዓቂቡ",empty:"ምርኢት CV ንምጅማር ስምኩም ኣእትዉ።",tip:"PDF ንምዕቃብ ኣብ print window “Save as PDF” ምረጹ።"}};
const enc=(xs:Item[])=>JSON.stringify(xs), dec=(s:string):Item[]=>{try{const x=JSON.parse(s);return Array.isArray(x)?x:[]}catch{return s? s.split("\n").filter(Boolean).map(x=>({title:x,place:"",date:"",detail:""})):[]}};
export default function CVStudio(){
 const[lang,setLang]=useState<Lang>("en"),[form,setForm]=useState<CV>(blank),[saved,setSaved]=useState<CV[]>([]),[status,setStatus]=useState(""),[photo,setPhoto]=useState(""),[work,setWork]=useState<Item[]>([]),[edu,setEdu]=useState<Item[]>([]),[cert,setCert]=useState<Item[]>([]),[showSaved,setShowSaved]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const t=labels[lang];
 const load=async()=>{try{setSaved(await(await fetch(api()+"/api/v1/career/cv")).json())}catch{}};
 useEffect(()=>{load()},[]);
 const set=(k:keyof CV,v:string)=>setForm({...form,[k]:v});
 const update=(kind:"work"|"edu"|"cert",i:number,k:keyof Item,v:string)=>{const src=kind==="work"?work:kind==="edu"?edu:cert;const next=src.map((x,n)=>n===i?{...x,[k]:v}:x);kind==="work"?setWork(next):kind==="edu"?setEdu(next):setCert(next)};
 const add=(kind:"work"|"edu"|"cert")=>{const x={title:"",place:"",date:"",detail:""};kind==="work"?setWork([...work,x]):kind==="edu"?setEdu([...edu,x]):setCert([...cert,x])};
 const remove=(kind:"work"|"edu"|"cert",i:number)=>{kind==="work"?setWork(work.filter((_,n)=>n!==i)):kind==="edu"?setEdu(edu.filter((_,n)=>n!==i)):setCert(cert.filter((_,n)=>n!==i))};
 const open=(cv:CV)=>{setForm(cv);setWork(dec(cv.experience));setEdu(dec(cv.education));setCert(dec(cv.certifications));setPhoto("");setShowSaved(false)};
 const fresh=()=>{setForm({...blank});setWork([]);setEdu([]);setCert([]);setPhoto("");setStatus("");setShowSaved(false)};
 const photoChange=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>setPhoto(String(r.result));r.readAsDataURL(f)};
 async function submit(e:FormEvent){e.preventDefault();const payload={...form,experience:enc(work),education:enc(edu),certifications:enc(cert)};delete payload.id;try{const r=await fetch(api()+"/api/v1/career/cv"+(form.id?"/"+form.id:""),{method:form.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw 0;const d=await r.json();setForm(d);setStatus("✓ "+t.saved);load()}catch{setStatus("Save failed")}}
 const ItemEditor=({kind,items}:{kind:"work"|"edu"|"cert",items:Item[]})=><div className="itemList">{items.map((x,i)=><div className="item" key={i}><button type="button" className="removeItem" onClick={()=>remove(kind,i)}>×</button><div className="two"><label>{t.position}<input value={x.title} onChange={e=>update(kind,i,"title",e.target.value)}/></label><label>{t.company}<input value={x.place} onChange={e=>update(kind,i,"place",e.target.value)}/></label></div><label>{t.date}<input value={x.date} onChange={e=>update(kind,i,"date",e.target.value)}/></label><label>{t.details}<textarea rows={3} value={x.detail} onChange={e=>update(kind,i,"detail",e.target.value)}/></label></div>)}</div>;
 return <main className="studio"><header><Link href="/">← {t.back}</Link><div className="topActions"><button onClick={()=>setShowSaved(!showSaved)}>{t.my} <b>{saved.length}</b></button><button onClick={fresh}>＋ {t.new}</button>{(["de","en","ti"] as Lang[]).map(l=><button className={lang===l?"on":""} onClick={()=>setLang(l)} key={l}>{l==="ti"?"ትግ":l.toUpperCase()}</button>)}</div></header>
 {showSaved&&<section className="drawer"><div><h2>{t.my}</h2><button onClick={()=>setShowSaved(false)}>×</button></div>{saved.map(cv=><article key={cv.id} onClick={()=>open(cv)}><span>{cv.first_name?.[0]}{cv.last_name?.[0]}</span><div><strong>{cv.cv_title}</strong><small>{cv.first_name} {cv.last_name} · {cv.profession||"CV"}</small></div><b>→</b></article>)}</section>}
 <section className="intro"><span>NEXORA · CV STUDIO</span><h1>{t.title}</h1><p>{t.sub}</p></section>
 <div className="builder"><form onSubmit={submit}><section className="photoBlock"><div className="photoCircle">{photo?<img src={photo} alt="Profile"/>:<span>{form.first_name?.[0]||"＋"}</span>}</div><div><h3>{t.photo}</h3><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>photoChange(e.target.files?.[0])}/><button type="button" onClick={()=>fileRef.current?.click()}>{t.upload}</button>{photo&&<button type="button" className="quiet" onClick={()=>setPhoto("")}>{t.remove}</button>}</div></section>
 <h2>{t.personal}</h2><label>{t.name}<input value={form.cv_title} onChange={e=>set("cv_title",e.target.value)}/></label><div className="two"><label>{t.first}<input required value={form.first_name} onChange={e=>set("first_name",e.target.value)}/></label><label>{t.last}<input required value={form.last_name} onChange={e=>set("last_name",e.target.value)}/></label></div><div className="two"><label>{t.email}<input value={form.email} onChange={e=>set("email",e.target.value)}/></label><label>{t.phone}<input value={form.phone} onChange={e=>set("phone",e.target.value)}/></label></div><div className="two"><label>{t.city}<input value={form.city} onChange={e=>set("city",e.target.value)}/></label><label>{t.address}<input value={form.address} onChange={e=>set("address",e.target.value)}/></label></div><label>{t.link}<input value={form.linkedin} onChange={e=>set("linkedin",e.target.value)}/></label>
 <h2>{t.career}</h2><label>{t.role}<input value={form.profession} onChange={e=>set("profession",e.target.value)}/></label><label>{t.summary}<textarea rows={4} value={form.summary} onChange={e=>set("summary",e.target.value)}/></label>
 <h2>{t.work}</h2><ItemEditor kind="work" items={work}/><button type="button" className="addBtn" onClick={()=>add("work")}>{t.addWork}</button>
 <h2>{t.edu}</h2><ItemEditor kind="edu" items={edu}/><button type="button" className="addBtn" onClick={()=>add("edu")}>{t.addEdu}</button>
 <h2>{t.cert}</h2><ItemEditor kind="cert" items={cert}/><button type="button" className="addBtn" onClick={()=>add("cert")}>{t.addCert}</button>
 <h2>{t.skills} & {t.langs}</h2><label>{t.skills}<textarea rows={4} value={form.skills} onChange={e=>set("skills",e.target.value)} placeholder="Cisco, VMware, Microsoft 365…"/></label><label>{t.langs}<textarea rows={4} value={form.languages} onChange={e=>set("languages",e.target.value)} placeholder="German — B2&#10;English — C1"/></label>
 <h2>{t.design}</h2><div className="templates">{templates.map(([id,name,badge])=><button type="button" key={id} onClick={()=>set("template",id)} className={"template "+id+(form.template===id?" selected":"")}><div className="mini"><i/><i/><i/><i/></div><span><strong>{name}</strong><em>{badge}</em></span></button>)}</div>
 <div className="saveRow"><button className="save">{form.id?t.update:t.save}</button><button type="button" className="pdf" onClick={()=>window.print()}>⇩ {t.download}</button><span>{status}</span></div><p className="printTip">{t.tip}</p></form>
 <aside><div className="previewHead"><span>{t.preview}</span><b>{form.template.toUpperCase()}</b></div><div id="cv-print" className={"paper "+form.template}>{form.first_name||form.last_name?<><div className="identity">{photo&&<img src={photo} alt="Profile"/>}<div><h1>{form.first_name} {form.last_name}</h1><h3>{form.profession}</h3><p>{[form.city,form.phone,form.email].filter(Boolean).join(" · ")}</p><p>{form.linkedin}</p></div></div>{form.summary&&<p className="summary">{form.summary}</p>}<CVSection title="EXPERIENCE" items={work}/><CVSection title="EDUCATION" items={edu}/><CVSection title="CERTIFICATES" items={cert}/>{form.skills&&<TextSection title="SKILLS" value={form.skills}/>} {form.languages&&<TextSection title="LANGUAGES" value={form.languages}/>}</>:<div className="empty">{t.empty}</div>}</div></aside></div></main>
}
function CVSection({title,items}:{title:string,items:Item[]}){if(!items.length)return null;return <section><h4>{title}</h4>{items.map((x,i)=><div className="cvItem" key={i}><div><strong>{x.title}</strong><span>{x.date}</span></div><b>{x.place}</b>{x.detail&&<p>{x.detail}</p>}</div>)}</section>}
function TextSection({title,value}:{title:string,value:string}){return <section><h4>{title}</h4><div className="chips">{value.split("\n").filter(Boolean).map((x,i)=><span key={i}>{x}</span>)}</div></section>}
